#! /bin/bash

. ~/scripts/grabcolors.sh

lo=$colo2
md=$colo4
hi=$colo1

while true; do
	echo -e "%{c}%{F${colo6}}\uf012%{F-} %{F${colo2}}$(ip -h route | grep default | awk '{ print $7 }')"
	sleep 60
done | lemonbar -p -d -a 1 -g 120x25+1476+8 -r 2 -R $colo6 -f "Nouveau IBM:size=10" -f "fontawesome:size=12" -B $bg -F $fg
