#! /bin/bash

. ~/scripts/grabcolors.sh

lo=$colo2
md=$colo4
hi=$colo1

while true; do
	echo -e "%{c}%{F$colo6}\uf2c8%{F-} $(sensors | grep 'Package' | awk '{print $4}')"
	sleep 10
done | lemonbar -p -d -a 1 -g 90x25+1366+8 -r 2 -R $colo6 -f "Nouveau IBM:size=10" -f "fontawesome:size=12" -B $bg -F $fg
